time add
wty1996/learning-js pull request #10
Opened 2017-08-02 10:14 UTC by wty1996

2017-08-02 10:42 UTC, wty1996 commented
计算器console无报错 ，=号后的计算结果不知到怎么表达 
时间js当前时间报错``Uncaught ReferenceError: today is not defined``
实际代码为
``var time = new [Date()](url)
hour =  today.getHours()
min = today.getMinutes()
miao = today.getSeconds()
``
@

2017-08-02 10:56 UTC, xiaoyuhen commented
today没定义把。你定义的是time

2017-08-03 05:05 UTC, xiaoyuhen requested changes

2017-08-03 05:05 UTC, xiaoyuhen commented on lesson3/task7/calculator.js
> +	if (screen === a) {
这个逻辑是不是没啥用，上面已经设置screen === a了，下面的if判断就没用了吧

2017-08-03 05:05 UTC, xiaoyuhen commented on lesson3/task7/calculator.js
> +		b = Number(sym[i])
b是从哪来的？

2017-08-03 05:05 UTC, xiaoyuhen commented on lesson3/task7/calculator.js
> +	c = Number(equ[i])
c是从哪来的

2017-08-03 05:05 UTC, xiaoyuhen commented on lesson3/task8/time.css
> +.miao {
second

2017-08-08 05:15 UTC, merged